name: bowhead-py31018
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.18
  - pip
  - numpy=1.26.4
  - scipy=1.15.2
  - matplotlib=3.10.6
  - pandas
  - scikit-learn=1.7.1
  - pip:
    - torchaudio==2.7.0
    - torchvision==0.22.0
    - torch==2.7.0
    - tensorboard
